import type { CanvasLayer, CanvasLayerType } from './types';
import { mm, newId } from './types';
import { DEFAULT_LINE_STROKE_PX, lineHeightMmFromStrokePx } from './ops/layerStyle';

export const DEFAULT_FIELD_KEYS = [
  { key: 'CENTRO', label: 'Centro' },
  { key: 'NIS', label: 'NIS' },
  { key: 'OT', label: 'Nro OT' },
  { key: 'DIRECCION', label: 'Dirección' },
  { key: 'LOCALIDAD', label: 'Localidad' },
  { key: 'DISTRITO', label: 'Distrito' },
  { key: 'ACTIVIDAD', label: 'Actividad' },
  { key: 'CONTRATA', label: 'Contrata' },
] as const;

export function createLayer(
  type: Exclude<CanvasLayerType, 'frame'>,
  overrides?: Partial<CanvasLayer>,
): CanvasLayer {
  const base: Record<Exclude<CanvasLayerType, 'frame'>, CanvasLayer> = {
    text: {
      id: newId(),
      type: 'text',
      name: 'Texto',
      value: 'Texto',
      cssVars: {
        '--width': mm(60),
        '--height': mm(8),
        '--translate-x': mm(20),
        '--translate-y': mm(30),
        '--color': '#222222',
        '--font-size': '11pt',
        '--font-family': 'Segoe UI, Arial, sans-serif',
        '--text-align': 'left',
        '--background-color': 'transparent',
      },
    },
    field: {
      id: newId(),
      type: 'field',
      name: 'Campo',
      value: '',
      cssVars: {
        '--width': mm(70),
        '--height': mm(8),
        '--translate-x': mm(20),
        '--translate-y': mm(45),
        '--color': '#111111',
        '--font-size': '10pt',
        '--font-family': 'Segoe UI, Arial, sans-serif',
        '--text-align': 'left',
        '--background-color': '#f5f5f5',
        '--border': '1px dashed #bbb',
      },
      meta: { key: 'DIRECCION', fallback: '-' },
    },
    logo: {
      id: newId(),
      type: 'logo',
      name: 'Logo',
      value: '',
      cssVars: {
        '--width': mm(45),
        '--height': mm(16),
        '--translate-x': mm(10),
        '--translate-y': mm(8),
        '--background-color': '#eef2ff',
        '--border': '1px dashed #94a3b8',
        '--object-fit': 'contain',
      },
      meta: { side: 'left' },
    },
    imageSlot: {
      id: newId(),
      type: 'imageSlot',
      name: 'Foto',
      value: '',
      cssVars: {
        '--width': mm(80),
        '--height': mm(60),
        '--translate-x': mm(20),
        '--translate-y': mm(80),
        '--background-color': '#f1f5f9',
        '--border': '1px dashed #94a3b8',
        '--object-fit': 'cover',
      },
      meta: { index: 0 },
    },
    image: {
      id: newId(),
      type: 'image',
      name: 'Imagen',
      value: '',
      cssVars: {
        '--width': mm(50),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(100),
        '--object-fit': 'cover',
        '--background-color': '#e2e8f0',
      },
    },
    rect: {
      id: newId(),
      type: 'rect',
      name: 'Rectangle',
      value: '',
      cssVars: {
        '--width': mm(50),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(100),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#000000',
        '--border-radius': '10px',
        '--opacity': '100',
      },
    },
    grid: {
      id: newId(),
      type: 'grid',
      name: 'Cuadrícula',
      value: '',
      cssVars: {
        '--width': mm(170),
        '--height': mm(120),
        '--translate-x': mm(20),
        '--translate-y': mm(80),
        '--background-color': 'transparent',
        '--border': '1px dashed #94a3b8',
      },
      meta: { cols: 2, rows: 2, gapMm: 2 },
    },
    group: {
      id: newId(),
      type: 'group',
      name: 'Grupo',
      value: '',
      cssVars: {
        '--width': mm(80),
        '--height': mm(60),
        '--translate-x': mm(20),
        '--translate-y': mm(80),
        '--background-color': 'transparent',
      },
    },
    table: {
      id: newId(),
      type: 'table',
      name: 'Tabla',
      value: '',
      cssVars: {
        '--width': mm(170),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(120),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#cbd5e1',
      },
      meta: { rowsData: JSON.stringify({ cells: [['Col A', 'Col B'], ['', '']] }) },
    },
    checkbox: {
      id: newId(),
      type: 'checkbox',
      name: 'Casilla',
      value: '',
      cssVars: {
        '--width': mm(6),
        '--height': mm(6),
        '--translate-x': mm(20),
        '--translate-y': mm(140),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#000000',
      },
      meta: { checked: false },
    },
    signature: {
      id: newId(),
      type: 'signature',
      name: 'Firma',
      value: '',
      cssVars: {
        '--width': mm(60),
        '--height': mm(20),
        '--translate-x': mm(20),
        '--translate-y': mm(160),
        '--background-color': 'transparent',
        '--border-width': '1px',
        '--border-color': '#000000',
      },
    },
    line: {
      id: newId(),
      type: 'line',
      name: 'Línea',
      value: '',
      cssVars: {
        '--width': mm(80),
        '--height': mm(Math.max(2, lineHeightMmFromStrokePx(DEFAULT_LINE_STROKE_PX))),
        '--translate-x': mm(20),
        '--translate-y': mm(180),
        '--background-color': 'transparent',
        '--fill-visible': '0',
        '--border-width': `${DEFAULT_LINE_STROKE_PX}px`,
        '--border-color': '#000000',
        '--stroke-align': 'center',
        '--stroke-visible': '1',
        '--stroke-opacity': '100',
        '--stroke-start': 'none',
        '--stroke-end': 'none',
      },
      meta: {
        path: {
          points: [
            { x: 0, y: 1 },
            { x: 80, y: 1 },
          ],
          closed: false,
        },
      },
    },
    ellipse: {
      id: newId(),
      type: 'ellipse',
      name: 'Elipse',
      value: '',
      cssVars: {
        '--width': mm(40),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(190),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#000000',
        '--border-radius': '50%',
      },
    },
    arrow: {
      id: newId(),
      type: 'arrow',
      name: 'Flecha',
      value: '',
      cssVars: {
        '--width': mm(50),
        '--height': mm(24),
        '--translate-x': mm(20),
        '--translate-y': mm(200),
        '--background-color': '#000000',
        '--opacity': '100',
      },
    },
    polygon: {
      id: newId(),
      type: 'polygon',
      name: 'Polígono',
      value: '',
      cssVars: {
        '--width': mm(40),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(210),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#000000',
        '--opacity': '100',
      },
    },
    star: {
      id: newId(),
      type: 'star',
      name: 'Estrella',
      value: '',
      cssVars: {
        '--width': mm(40),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(220),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#000000',
        '--opacity': '100',
      },
    },
    diamond: {
      id: newId(),
      type: 'diamond',
      name: 'Rombo',
      value: '',
      cssVars: {
        '--width': mm(40),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(230),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#000000',
        '--opacity': '100',
      },
    },
    hexagon: {
      id: newId(),
      type: 'hexagon',
      name: 'Hexágono',
      value: '',
      cssVars: {
        '--width': mm(40),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(240),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#000000',
        '--opacity': '100',
      },
    },
    pentagon: {
      id: newId(),
      type: 'pentagon',
      name: 'Pentágono',
      value: '',
      cssVars: {
        '--width': mm(40),
        '--height': mm(40),
        '--translate-x': mm(20),
        '--translate-y': mm(250),
        '--background-color': '#ffffff',
        '--border-width': '1px',
        '--border-color': '#000000',
        '--opacity': '100',
      },
    },

  };

  return { ...base[type], ...overrides, id: overrides?.id ?? newId(), type };
}
