export const CANVAS_SHORTCUTS: Array<{ keys: string; action: string }> = [
  { keys: 'V', action: 'Seleccionar' },
  { keys: 'H / Espacio', action: 'Mano (pan)' },
  { keys: 'R / O / L', action: 'Rectángulo / Elipse / Línea' },
  { keys: 'Shift+L / P / S / D / H / N', action: 'Flecha / Polígono / Estrella / Rombo / Hexágono / Pentágono' },
  { keys: 'P / C (línea) · U', action: 'Curvar / cortar línea · lazo' },
  { keys: 'Ctrl+Shift+K', action: 'Imagen' },
  { keys: 'T / F', action: 'Texto / Campo Excel' },
  { keys: 'Doble clic / Enter', action: 'Editar texto/campo, grupo, grid o línea' },
  { keys: 'Teclear (texto sel.)', action: 'Escribir / reemplazar en el lienzo' },
  { keys: 'I / M / G / B', action: 'Slot / Imagen / Grid / Tabla' },
  { keys: 'Ctrl+Z · Ctrl+Shift+Z · Ctrl+Y', action: 'Deshacer / rehacer' },
  { keys: 'Ctrl+D', action: 'Duplicar' },
  { keys: 'Ctrl+C · Ctrl+V', action: 'Copiar / pegar (con hijos)' },
  { keys: 'Ctrl+Shift+V', action: 'Pegar en el sitio' },
  { keys: 'Ctrl+G · Ctrl+Shift+G', action: 'Agrupar / desagrupar' },
  { keys: 'F2', action: 'Renombrar capa seleccionada' },
  { keys: 'Ctrl+Shift+L', action: 'Bloquear / desbloquear selección' },
  { keys: 'Ctrl+Shift+H', action: 'Ocultar / mostrar selección' },
  { keys: '] / [', action: 'Al frente / Al fondo (entre hermanos)' },
  { keys: 'Ctrl+] · Ctrl+[', action: 'Adelante / atrás (un paso)' },
  { keys: 'Esc', action: 'Salir de edición / volver al padre / deseleccionar' },
  { keys: 'Flechas', action: 'Mover 1 mm (⇧ = 10 mm, Alt = 0.1 mm)' },
  { keys: 'Arrastrar vacío', action: 'Marquee (selección)' },
  { keys: 'Shift + resize', action: 'Bloquear proporción' },
  { keys: 'Alt + resize', action: 'Escalar desde el centro' },
  { keys: 'Shift + rotar', action: 'Snap 15°' },
  { keys: 'Supr / Backspace', action: 'Eliminar' },
  { keys: 'Ctrl+S', action: 'Guardar' },
  { keys: 'Ctrl+Scroll', action: 'Zoom al cursor' },
  { keys: 'Ctrl++ · Ctrl+-', action: 'Acercar / alejar' },
  { keys: 'Ctrl+0', action: 'Zoom 100%' },
  { keys: 'Shift+1', action: 'Zoom para encajar' },
  { keys: 'Shift+2', action: 'Zoom a la selección' },
  { keys: 'Shift+R', action: 'Mostrar / ocultar reglas' },
  { keys: "Shift+'", action: 'Snap a cuadrícula' },
  { keys: 'Ctrl+\\', action: 'Mostrar / ocultar paneles' },
  { keys: 'Alt + arrastrar', action: 'Duplicar y mover' },
  { keys: 'Alt+A/D/W/S', action: 'Alinear izq/der/arriba/abajo' },
  { keys: 'Alt+H/V', action: 'Alinear centro / medio' },
  { keys: 'Alt+X/Y', action: 'Distribuir horizontal / vertical' },
  { keys: 'Ctrl + arrastrar', action: 'Desactivar snap' },
  { keys: 'Reglas', action: 'Arrastrar para crear guías' },
];
