/** Keyboard shortcuts shown in Canvas design mode (Spanish UI). */
export const CANVAS_SHORTCUTS: Array<{ keys: string; action: string }> = [
  { keys: 'V', action: 'Seleccionar' },
  { keys: 'H / Espacio', action: 'Mano (pan)' },
  { keys: 'R / O / L', action: 'Rectángulo / Elipse / Línea' },
  { keys: 'Shift+L', action: 'Flecha' },
  { keys: 'Ctrl+Shift+K', action: 'Imagen' },
  { keys: 'T / F', action: 'Texto / Campo Excel' },
  { keys: 'Doble clic / Enter', action: 'Editar texto (campo → clave Excel)' },
  { keys: 'Teclear (texto sel.)', action: 'Escribir / reemplazar en el lienzo' },
  { keys: 'Esc (editando)', action: 'Salir de edición de texto' },
  { keys: 'I / M / G / B', action: 'Slot / Imagen / Grid / Tabla' },
  { keys: 'Ctrl+Z / ⇧Z', action: 'Deshacer / Rehacer' },
  { keys: 'Ctrl+D', action: 'Duplicar' },
  { keys: 'Ctrl+C / V', action: 'Copiar / Pegar' },
  { keys: 'Ctrl+G / ⇧G', action: 'Agrupar / Desagrupar' },
  { keys: '] / [', action: 'Al frente / Al fondo' },
  { keys: 'Ctrl+] / [', action: 'Adelante / Atrás (un paso)' },
  { keys: 'Enter (grupo/grid)', action: 'Seleccionar hijos' },
  { keys: 'Flechas', action: 'Mover 1 mm (⇧ = 10 mm)' },
  { keys: 'Arrastrar vacío', action: 'Marquee (selección)' },
  { keys: 'Shift + resize', action: 'Bloquear proporción' },
  { keys: 'Shift + rotar', action: 'Snap 15°' },
  { keys: 'Supr', action: 'Eliminar' },
  { keys: 'Ctrl+S', action: 'Guardar' },
  { keys: 'Ctrl+Scroll', action: 'Zoom al cursor' },
  { keys: 'Ctrl++ / -', action: 'Acercar / Alejar' },
  { keys: 'Ctrl+0', action: 'Zoom 100%' },
  { keys: 'Shift+1', action: 'Zoom para encajar' },
];
