"""Configuración personalizable de colores/temas de la aplicación."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from backend.utils.paths import user_data_path

logger = logging.getLogger(__name__)

DEFAULT_THEME: dict[str, str] = {
    "name": "Slate Professional",
    "bg": "#0F172A",
    "bg_secondary": "#172033",
    "fg": "#F8FAFC",
    "fg_muted": "#94A3B8",
    "fg_secondary": "#CBD5E1",
    "fg_tertiary": "#64748B",
    "accent": "#3B82F6",
    "accent_light": "#93C5FD",
    "accent_hover": "#2563EB",
    "accent_dark": "#1E40AF",
    "border": "#334155",
    "blue_hover": "#14B8A6",
    "error": "#EF4444",
    "warning": "#F59E0B",
    "success": "#22C55E",
    "orange": "#38BDF8",
}

PRESETS: dict[str, dict[str, str]] = {
    "Slate Professional": dict(DEFAULT_THEME),
    "Graphite Focus": {
        "name": "Graphite Focus",
        "bg": "#111315",
        "bg_secondary": "#1B1F23",
        "fg": "#F2F4F7",
        "fg_muted": "#98A2B3",
        "fg_secondary": "#D0D5DD",
        "fg_tertiary": "#667085",
        "accent": "#A3E635",
        "accent_light": "#D9F99D",
        "accent_hover": "#84CC16",
        "accent_dark": "#4D7C0F",
        "border": "#30363D",
        "blue_hover": "#38BDF8",
        "error": "#F97066",
        "warning": "#FDB022",
        "success": "#32D583",
        "orange": "#F79009",
    },
    "Porcelain Light": {
        "name": "Porcelain Light",
        "bg": "#F7F8FA",
        "bg_secondary": "#FFFFFF",
        "fg": "#182230",
        "fg_muted": "#667085",
        "fg_secondary": "#475467",
        "fg_tertiary": "#98A2B3",
        "accent": "#475467",
        "accent_light": "#D0D5DD",
        "accent_hover": "#344054",
        "accent_dark": "#101828",
        "border": "#D0D5DD",
        "blue_hover": "#0EA5E9",
        "error": "#D92D20",
        "warning": "#DC6803",
        "success": "#039855",
        "orange": "#1570EF",
    },
    "Steel Blue": {
        "name": "Steel Blue",
        "bg": "#08111F",
        "bg_secondary": "#102033",
        "fg": "#E6EEF8",
        "fg_muted": "#8FA4BD",
        "fg_secondary": "#B8C7D9",
        "fg_tertiary": "#61758C",
        "accent": "#38BDF8",
        "accent_light": "#BAE6FD",
        "accent_hover": "#0EA5E9",
        "accent_dark": "#0369A1",
        "border": "#22364F",
        "blue_hover": "#22D3EE",
        "error": "#FB7185",
        "warning": "#FBBF24",
        "success": "#34D399",
        "orange": "#60A5FA",
    },
    "Olive Operations": {
        "name": "Olive Operations",
        "bg": "#10140D",
        "bg_secondary": "#1B2316",
        "fg": "#F3F7EF",
        "fg_muted": "#A8B79A",
        "fg_secondary": "#CED9C2",
        "fg_tertiary": "#748566",
        "accent": "#84CC16",
        "accent_light": "#BEF264",
        "accent_hover": "#65A30D",
        "accent_dark": "#365314",
        "border": "#34452A",
        "blue_hover": "#2DD4BF",
        "error": "#F87171",
        "warning": "#FACC15",
        "success": "#4ADE80",
        "orange": "#A3E635",
    },
    "Copper Night": {
        "name": "Copper Night",
        "bg": "#17110D",
        "bg_secondary": "#241A14",
        "fg": "#FFF7ED",
        "fg_muted": "#BFA38C",
        "fg_secondary": "#E7D1BC",
        "fg_tertiary": "#8E6F59",
        "accent": "#F97316",
        "accent_light": "#FDBA74",
        "accent_hover": "#EA580C",
        "accent_dark": "#9A3412",
        "border": "#493122",
        "blue_hover": "#38BDF8",
        "error": "#FB7185",
        "warning": "#FBBF24",
        "success": "#84CC16",
        "orange": "#FB923C",
    },
    "Mono Contrast": {
        "name": "Mono Contrast",
        "bg": "#000000",
        "bg_secondary": "#111111",
        "fg": "#ffffff",
        "fg_muted": "#ffffff",
        "fg_secondary": "#cccccc",
        "fg_tertiary": "#999999",
        "accent": "#ffff00",
        "accent_light": "#ffff66",
        "accent_hover": "#00ffff",
        "accent_dark": "#cccc00",
        "border": "#ffffff",
        "blue_hover": "#00ffff",
        "error": "#ff0000",
        "warning": "#ffaa00",
        "success": "#00ff00",
        "orange": "#ff8800",
    },
    "Solar Claro": {
        "name": "Solar Claro",
        "bg": "#F8FAFC",
        "bg_secondary": "#FFFFFF",
        "fg": "#172033",
        "fg_muted": "#64748B",
        "fg_secondary": "#475569",
        "fg_tertiary": "#94A3B8",
        "accent": "#0EA5E9",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0284C7",
        "accent_dark": "#075985",
        "border": "#CBD5E1",
        "blue_hover": "#14B8A6",
        "error": "#DC2626",
        "warning": "#D97706",
        "success": "#16A34A",
        "orange": "#F59E0B",
    },
    "Bosque Operativo": {
        "name": "Bosque Operativo",
        "bg": "#07130F",
        "bg_secondary": "#10231D",
        "fg": "#F0FDF4",
        "fg_muted": "#A7C8B6",
        "fg_secondary": "#86A998",
        "fg_tertiary": "#638173",
        "accent": "#22C55E",
        "accent_light": "#86EFAC",
        "accent_hover": "#16A34A",
        "accent_dark": "#166534",
        "border": "#235341",
        "blue_hover": "#2DD4BF",
        "error": "#F87171",
        "warning": "#FBBF24",
        "success": "#4ADE80",
        "orange": "#A3E635",
    },
    "Amanecer Ambar": {
        "name": "Amanecer Ambar",
        "bg": "#1C1208",
        "bg_secondary": "#2A1A0D",
        "fg": "#FFF7ED",
        "fg_muted": "#D6B08A",
        "fg_secondary": "#C6925C",
        "fg_tertiary": "#92683C",
        "accent": "#F59E0B",
        "accent_light": "#FCD34D",
        "accent_hover": "#D97706",
        "accent_dark": "#92400E",
        "border": "#6B3E18",
        "blue_hover": "#38BDF8",
        "error": "#FB7185",
        "warning": "#FBBF24",
        "success": "#84CC16",
        "orange": "#FB923C",
    },
    "Neon Grid": {
        "name": "Neon Grid",
        "bg": "#070713",
        "bg_secondary": "#111126",
        "fg": "#F8FAFC",
        "fg_muted": "#A5B4FC",
        "fg_secondary": "#C4B5FD",
        "fg_tertiary": "#818CF8",
        "accent": "#22D3EE",
        "accent_light": "#67E8F9",
        "accent_hover": "#A855F7",
        "accent_dark": "#0891B2",
        "border": "#312E81",
        "blue_hover": "#F472B6",
        "error": "#FF4D8D",
        "warning": "#FACC15",
        "success": "#34D399",
        "orange": "#A855F7",
    },
    "Midnight Ocean": {
        "name": "Midnight Ocean",
        "bg": "#0A1628",
        "bg_secondary": "#142238",
        "fg": "#F0F9FF",
        "fg_muted": "#94A3B8",
        "fg_secondary": "#CBD5E1",
        "fg_tertiary": "#64748B",
        "accent": "#0EA5E9",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0284C7",
        "accent_dark": "#075985",
        "border": "#1E3A5F",
        "blue_hover": "#22D3EE",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#38BDF8",
    },
    "Forest Zen": {
        "name": "Forest Zen",
        "bg": "#0D1F14",
        "bg_secondary": "#16291D",
        "fg": "#F0FDF4",
        "fg_muted": "#86EFAC",
        "fg_secondary": "#BBF7D0",
        "fg_tertiary": "#4ADE80",
        "accent": "#22C55E",
        "accent_light": "#86EFAC",
        "accent_hover": "#16A34A",
        "accent_dark": "#15803D",
        "border": "#1E3A28",
        "blue_hover": "#14B8A6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#84CC16",
    },
    "Royal Purple": {
        "name": "Royal Purple",
        "bg": "#1A0B2E",
        "bg_secondary": "#2D1B4E",
        "fg": "#F5F3FF",
        "fg_muted": "#C4B5FD",
        "fg_secondary": "#DDD6FE",
        "fg_tertiary": "#A78BFA",
        "accent": "#8B5CF6",
        "accent_light": "#C4B5FD",
        "accent_hover": "#7C3AED",
        "accent_dark": "#5B21B6",
        "border": "#4C1D95",
        "blue_hover": "#EC4899",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F59E0B",
    },
    "Rose Quartz": {
        "name": "Rose Quartz",
        "bg": "#1F1115",
        "bg_secondary": "#2E1A20",
        "fg": "#FFF1F2",
        "fg_muted": "#FDA4AF",
        "fg_secondary": "#FECDD3",
        "fg_tertiary": "#FB7185",
        "accent": "#EC4899",
        "accent_light": "#F9A8D4",
        "accent_hover": "#DB2777",
        "accent_dark": "#BE185D",
        "border": "#4A1C24",
        "blue_hover": "#8B5CF6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F472B6",
    },
    "Arctic Frost": {
        "name": "Arctic Frost",
        "bg": "#F8FAFC",
        "bg_secondary": "#FFFFFF",
        "fg": "#0F172A",
        "fg_muted": "#64748B",
        "fg_secondary": "#475569",
        "fg_tertiary": "#94A3B8",
        "accent": "#0EA5E9",
        "accent_light": "#BAE6FD",
        "accent_hover": "#0284C7",
        "accent_dark": "#075985",
        "border": "#E2E8F0",
        "blue_hover": "#06B6D4",
        "error": "#DC2626",
        "warning": "#D97706",
        "success": "#059669",
        "orange": "#0EA5E9",
    },
    "Ember Glow": {
        "name": "Ember Glow",
        "bg": "#1A1208",
        "bg_secondary": "#2A1A0D",
        "fg": "#FFFBEB",
        "fg_muted": "#FCD34D",
        "fg_secondary": "#FDE68A",
        "fg_tertiary": "#FBBF24",
        "accent": "#F59E0B",
        "accent_light": "#FCD34D",
        "accent_hover": "#D97706",
        "accent_dark": "#B45309",
        "border": "#422006",
        "blue_hover": "#38BDF8",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#FB923C",
    },
    "Slate Modern": {
        "name": "Slate Modern",
        "bg": "#0F172A",
        "bg_secondary": "#1E293B",
        "fg": "#F8FAFC",
        "fg_muted": "#94A3B8",
        "fg_secondary": "#CBD5E1",
        "fg_tertiary": "#64748B",
        "accent": "#3B82F6",
        "accent_light": "#93C5FD",
        "accent_hover": "#2563EB",
        "accent_dark": "#1E40AF",
        "border": "#334155",
        "blue_hover": "#06B6D4",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#38BDF8",
    },
    "Aurora Borealis": {
        "name": "Aurora Borealis",
        "bg": "#0A0F1A",
        "bg_secondary": "#141B2D",
        "fg": "#F0F9FF",
        "fg_muted": "#7DD3FC",
        "fg_secondary": "#A5F3FC",
        "fg_tertiary": "#22D3EE",
        "accent": "#06B6D4",
        "accent_light": "#67E8F9",
        "accent_hover": "#0891B2",
        "accent_dark": "#0E7490",
        "border": "#164E63",
        "blue_hover": "#A855F7",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#22D3EE",
    },
    "Minimalist Cream": {
        "name": "Minimalist Cream",
        "bg": "#FFFBF0",
        "bg_secondary": "#FFFFFF",
        "fg": "#1C1917",
        "fg_muted": "#78716C",
        "fg_secondary": "#57534E",
        "fg_tertiary": "#A8A29E",
        "accent": "#78716C",
        "accent_light": "#D6D3D1",
        "accent_hover": "#57534E",
        "accent_dark": "#44403C",
        "border": "#E7E5E4",
        "blue_hover": "#0EA5E9",
        "error": "#DC2626",
        "warning": "#D97706",
        "success": "#059669",
        "orange": "#D97706",
    },
    "Cyberpunk": {
        "name": "Cyberpunk",
        "bg": "#050505",
        "bg_secondary": "#0A0A0A",
        "fg": "#FFFFFF",
        "fg_muted": "#FF00FF",
        "fg_secondary": "#00FFFF",
        "fg_tertiary": "#FFFF00",
        "accent": "#FF00FF",
        "accent_light": "#FF66FF",
        "accent_hover": "#CC00CC",
        "accent_dark": "#990099",
        "border": "#333333",
        "blue_hover": "#00FFFF",
        "error": "#FF0000",
        "warning": "#FFFF00",
        "success": "#00FF00",
        "orange": "#FF6600",
    },
    "Deep Space": {
        "name": "Deep Space",
        "bg": "#030712",
        "bg_secondary": "#0F172A",
        "fg": "#F8FAFC",
        "fg_muted": "#6366F1",
        "fg_secondary": "#818CF8",
        "fg_tertiary": "#4F46E5",
        "accent": "#6366F1",
        "accent_light": "#A5B4FC",
        "accent_hover": "#4F46E5",
        "accent_dark": "#3730A3",
        "border": "#1E1B4B",
        "blue_hover": "#22D3EE",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#8B5CF6",
    },
    "Golden Hour": {
        "name": "Golden Hour",
        "bg": "#1C1917",
        "bg_secondary": "#292524",
        "fg": "#FFFBEB",
        "fg_muted": "#FCD34D",
        "fg_secondary": "#FDE68A",
        "fg_tertiary": "#FBBF24",
        "accent": "#F59E0B",
        "accent_light": "#FCD34D",
        "accent_hover": "#D97706",
        "accent_dark": "#B45309",
        "border": "#44403C",
        "blue_hover": "#3B82F6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#FB923C",
    },
    "Lavender Dreams": {
        "name": "Lavender Dreams",
        "bg": "#1E1B4B",
        "bg_secondary": "#312E81",
        "fg": "#F5F3FF",
        "fg_muted": "#C4B5FD",
        "fg_secondary": "#DDD6FE",
        "fg_tertiary": "#A78BFA",
        "accent": "#8B5CF6",
        "accent_light": "#DDD6FE",
        "accent_hover": "#7C3AED",
        "accent_dark": "#5B21B6",
        "border": "#4338CA",
        "blue_hover": "#EC4899",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F472B6",
    },
    "Ocean Breeze": {
        "name": "Ocean Breeze",
        "bg": "#0C4A6E",
        "bg_secondary": "#075985",
        "fg": "#F0F9FF",
        "fg_muted": "#7DD3FC",
        "fg_secondary": "#BAE6FD",
        "fg_tertiary": "#38BDF8",
        "accent": "#0EA5E9",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0284C7",
        "accent_dark": "#0369A1",
        "border": "#0C4A6E",
        "blue_hover": "#22D3EE",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#06B6D4",
    },
    "Mars Red": {
        "name": "Mars Red",
        "bg": "#1C0A0A",
        "bg_secondary": "#2D1313",
        "fg": "#FEF2F2",
        "fg_muted": "#FCA5A5",
        "fg_secondary": "#FECACA",
        "fg_tertiary": "#F87171",
        "accent": "#EF4444",
        "accent_light": "#FCA5A5",
        "accent_hover": "#DC2626",
        "accent_dark": "#B91C1C",
        "border": "#450A0A",
        "blue_hover": "#3B82F6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F97316",
    },
    "Soft Pastel": {
        "name": "Soft Pastel",
        "bg": "#FAF7F5",
        "bg_secondary": "#FFFFFF",
        "fg": "#2C2420",
        "fg_muted": "#8C7B73",
        "fg_secondary": "#6B5E57",
        "fg_tertiary": "#A89B93",
        "accent": "#D4A373",
        "accent_light": "#E9C496",
        "accent_hover": "#B88A5A",
        "accent_dark": "#9A7048",
        "border": "#E8DDD5",
        "blue_hover": "#7DB9A8",
        "error": "#E07A7A",
        "warning": "#D4A373",
        "success": "#7DB9A8",
        "orange": "#E9C496",
    },
    "Nordic Frost": {
        "name": "Nordic Frost",
        "bg": "#F0F4F8",
        "bg_secondary": "#FFFFFF",
        "fg": "#1A202C",
        "fg_muted": "#4A5568",
        "fg_secondary": "#2D3748",
        "fg_tertiary": "#718096",
        "accent": "#4A90A4",
        "accent_light": "#90CDF4",
        "accent_hover": "#2C6F8A",
        "accent_dark": "#1A4A5E",
        "border": "#CBD5E0",
        "blue_hover": "#38B2AC",
        "error": "#E53E3E",
        "warning": "#DD6B20",
        "success": "#38A169",
        "orange": "#ED8936",
    },
    "Sakura Garden": {
        "name": "Sakura Garden",
        "bg": "#FFF5F7",
        "bg_secondary": "#FFFFFF",
        "fg": "#2D1F23",
        "fg_muted": "#8B6B73",
        "fg_secondary": "#6B4E56",
        "fg_tertiary": "#A88B93",
        "accent": "#EC407A",
        "accent_light": "#F48FB1",
        "accent_hover": "#D81B60",
        "accent_dark": "#AD1457",
        "border": "#F8BBD0",
        "blue_hover": "#26C6DA",
        "error": "#E53935",
        "warning": "#FB8C00",
        "success": "#43A047",
        "orange": "#FF8A65",
    },
    "Terminal Matrix": {
        "name": "Terminal Matrix",
        "bg": "#050805",
        "bg_secondary": "#0A120A",
        "fg": "#E8F5E9",
        "fg_muted": "#81C784",
        "fg_secondary": "#A5D6A7",
        "fg_tertiary": "#4CAF50",
        "accent": "#00E676",
        "accent_light": "#69F0AE",
        "accent_hover": "#00C853",
        "accent_dark": "#009624",
        "border": "#1B3A1B",
        "blue_hover": "#18FFFF",
        "error": "#FF5252",
        "warning": "#FFD740",
        "success": "#69F0AE",
        "orange": "#FFAB40",
    },
    "Obsidian Ember": {
        "name": "Obsidian Ember",
        "bg": "#0D0B0A",
        "bg_secondary": "#1A1614",
        "fg": "#FFF8E1",
        "fg_muted": "#FFB74D",
        "fg_secondary": "#FFE0B2",
        "fg_tertiary": "#BF8A4E",
        "accent": "#FF9100",
        "accent_light": "#FFD180",
        "accent_hover": "#FF6D00",
        "accent_dark": "#BF360C",
        "border": "#3E2723",
        "blue_hover": "#00BCD4",
        "error": "#FF5252",
        "warning": "#FFD740",
        "success": "#69F0AE",
        "orange": "#FFAB40",
    },
    "Twilight Lavender": {
        "name": "Twilight Lavender",
        "bg": "#1A1520",
        "bg_secondary": "#252030",
        "fg": "#F3E5F5",
        "fg_muted": "#CE93D8",
        "fg_secondary": "#E1BEE7",
        "fg_tertiary": "#AB47BC",
        "accent": "#AB47BC",
        "accent_light": "#CE93D8",
        "accent_hover": "#8E24AA",
        "accent_dark": "#6A1B9A",
        "border": "#4A148C",
        "blue_hover": "#26C6DA",
        "error": "#EF5350",
        "warning": "#FFA726",
        "success": "#66BB6A",
        "orange": "#FF8A65",
    },
    "Mint Chocolate": {
        "name": "Mint Chocolate",
        "bg": "#0F1512",
        "bg_secondary": "#182620",
        "fg": "#E8F5E9",
        "fg_muted": "#80CBC4",
        "fg_secondary": "#A7D8C9",
        "fg_tertiary": "#4DB6AC",
        "accent": "#26A69A",
        "accent_light": "#80CBC4",
        "accent_hover": "#00897B",
        "accent_dark": "#00695C",
        "border": "#264D40",
        "blue_hover": "#4DB6AC",
        "error": "#EF5350",
        "warning": "#FFB74D",
        "success": "#66BB6A",
        "orange": "#FF8A65",
    },
    "Coral Sunset": {
        "name": "Coral Sunset",
        "bg": "#1A1210",
        "bg_secondary": "#251A16",
        "fg": "#FFF3E0",
        "fg_muted": "#FFAB91",
        "fg_secondary": "#FFCCBC",
        "fg_tertiary": "#BF360C",
        "accent": "#FF7043",
        "accent_light": "#FFAB91",
        "accent_hover": "#F4511E",
        "accent_dark": "#BF360C",
        "border": "#3E2723",
        "blue_hover": "#40C4FF",
        "error": "#FF5252",
        "warning": "#FFD740",
        "success": "#69F0AE",
        "orange": "#FFAB40",
    },
    "Paper White": {
        "name": "Paper White",
        "bg": "#FFFFFF",
        "bg_secondary": "#F8FAFC",
        "fg": "#0F172A",
        "fg_muted": "#475569",
        "fg_secondary": "#334155",
        "fg_tertiary": "#94A3B8",
        "accent": "#0F172A",
        "accent_light": "#CBD5E1",
        "accent_hover": "#1E293B",
        "accent_dark": "#020617",
        "border": "#E2E8F0",
        "blue_hover": "#0EA5E9",
        "error": "#DC2626",
        "warning": "#D97706",
        "success": "#059669",
        "orange": "#F59E0B",
    },
    "Deep Forest": {
        "name": "Deep Forest",
        "bg": "#08140E",
        "bg_secondary": "#11221A",
        "fg": "#ECFDF5",
        "fg_muted": "#6EE7B7",
        "fg_secondary": "#A7F3D0",
        "fg_tertiary": "#34D399",
        "accent": "#059669",
        "accent_light": "#34D399",
        "accent_hover": "#047857",
        "accent_dark": "#065F46",
        "border": "#1E3A2F",
        "blue_hover": "#2DD4BF",
        "error": "#F87171",
        "warning": "#FBBF24",
        "success": "#34D399",
        "orange": "#A3E635",
    },
}

_CONFIG_PATH: Path | None = None


def _config_file() -> Path:
    global _CONFIG_PATH
    if _CONFIG_PATH is None:
        _CONFIG_PATH = user_data_path("theme_config.json")
    return _CONFIG_PATH


def load_theme() -> dict[str, str]:
    """Carga el tema desde disco o retorna el default."""
    path = _config_file()
    if path.exists():
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict) and "bg" in data:
                theme = dict(DEFAULT_THEME)
                theme.update(data)
                return theme
        except (json.JSONDecodeError, OSError, TypeError) as exc:
            logger.warning("Error leyendo configuración de tema, usando default: %s", exc)
    return dict(DEFAULT_THEME)


def save_theme(theme: dict[str, Any]) -> dict[str, str]:
    """Guarda el tema en disco."""
    path = _config_file()
    validated: dict[str, str] = {}
    for k, v in theme.items():
        if isinstance(v, str) and v.startswith("#"):
            validated[k] = v
        else:
            validated[k] = str(v)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(validated, f, indent=2, ensure_ascii=False)
    return validated


def reset_theme() -> dict[str, str]:
    """Restaura el tema por defecto."""
    save_theme(DEFAULT_THEME)
    return dict(DEFAULT_THEME)


def get_preset_names() -> list[str]:
    """Retorna la lista de nombres de presets disponibles."""
    return list(PRESETS.keys())


def load_preset(name: str) -> dict[str, str]:
    """Retorna una copia del preset solicitado o el default si no existe."""
    preset = PRESETS.get(name)
    if preset:
        return dict(preset)
    return dict(DEFAULT_THEME)
