"""Configuración personalizable de colores/temas de la aplicación."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from backend.utils.paths import user_data_path

logger = logging.getLogger(__name__)

DEFAULT_THEME: dict[str, str] = {
    "name": "Slate Professional",
    "bg": "#0F172A",
    "bg_secondary": "#172033",
    "fg": "#F8FAFC",
    "fg_muted": "#94A3B8",
    "fg_secondary": "#CBD5E1",
    "fg_tertiary": "#64748B",
    "accent": "#3B82F6",
    "accent_light": "#93C5FD",
    "accent_hover": "#2563EB",
    "accent_dark": "#1E40AF",
    "border": "#334155",
    "blue_hover": "#14B8A6",
    "error": "#EF4444",
    "warning": "#F59E0B",
    "success": "#22C55E",
    "orange": "#38BDF8",
}

PRESETS: dict[str, dict[str, str]] = {
    "Slate Professional": dict(DEFAULT_THEME),
    "Graphite Focus": {
        "name": "Graphite Focus",
        "bg": "#111315",
        "bg_secondary": "#1B1F23",
        "fg": "#F2F4F7",
        "fg_muted": "#98A2B3",
        "fg_secondary": "#D0D5DD",
        "fg_tertiary": "#667085",
        "accent": "#A3E635",
        "accent_light": "#D9F99D",
        "accent_hover": "#84CC16",
        "accent_dark": "#4D7C0F",
        "border": "#30363D",
        "blue_hover": "#38BDF8",
        "error": "#F97066",
        "warning": "#FDB022",
        "success": "#32D583",
        "orange": "#F79009",
    },
    "Porcelain Light": {
        "name": "Porcelain Light",
        "bg": "#F7F8FA",
        "bg_secondary": "#FFFFFF",
        "fg": "#182230",
        "fg_muted": "#667085",
        "fg_secondary": "#475467",
        "fg_tertiary": "#98A2B3",
        "accent": "#475467",
        "accent_light": "#D0D5DD",
        "accent_hover": "#344054",
        "accent_dark": "#101828",
        "border": "#D0D5DD",
        "blue_hover": "#0EA5E9",
        "error": "#D92D20",
        "warning": "#DC6803",
        "success": "#039855",
        "orange": "#1570EF",
    },
    "Steel Blue": {
        "name": "Steel Blue",
        "bg": "#08111F",
        "bg_secondary": "#102033",
        "fg": "#E6EEF8",
        "fg_muted": "#8FA4BD",
        "fg_secondary": "#B8C7D9",
        "fg_tertiary": "#61758C",
        "accent": "#38BDF8",
        "accent_light": "#BAE6FD",
        "accent_hover": "#0EA5E9",
        "accent_dark": "#0369A1",
        "border": "#22364F",
        "blue_hover": "#22D3EE",
        "error": "#FB7185",
        "warning": "#FBBF24",
        "success": "#34D399",
        "orange": "#60A5FA",
    },
    "Olive Operations": {
        "name": "Olive Operations",
        "bg": "#10140D",
        "bg_secondary": "#1B2316",
        "fg": "#F3F7EF",
        "fg_muted": "#A8B79A",
        "fg_secondary": "#CED9C2",
        "fg_tertiary": "#748566",
        "accent": "#84CC16",
        "accent_light": "#BEF264",
        "accent_hover": "#65A30D",
        "accent_dark": "#365314",
        "border": "#34452A",
        "blue_hover": "#2DD4BF",
        "error": "#F87171",
        "warning": "#FACC15",
        "success": "#4ADE80",
        "orange": "#A3E635",
    },
    "Copper Night": {
        "name": "Copper Night",
        "bg": "#17110D",
        "bg_secondary": "#241A14",
        "fg": "#FFF7ED",
        "fg_muted": "#BFA38C",
        "fg_secondary": "#E7D1BC",
        "fg_tertiary": "#8E6F59",
        "accent": "#F97316",
        "accent_light": "#FDBA74",
        "accent_hover": "#EA580C",
        "accent_dark": "#9A3412",
        "border": "#493122",
        "blue_hover": "#38BDF8",
        "error": "#FB7185",
        "warning": "#FBBF24",
        "success": "#84CC16",
        "orange": "#FB923C",
    },
    "Mono Contrast": {
        "name": "Mono Contrast",
        "bg": "#000000",
        "bg_secondary": "#111111",
        "fg": "#ffffff",
        "fg_muted": "#ffffff",
        "fg_secondary": "#cccccc",
        "fg_tertiary": "#999999",
        "accent": "#ffff00",
        "accent_light": "#ffff66",
        "accent_hover": "#00ffff",
        "accent_dark": "#cccc00",
        "border": "#ffffff",
        "blue_hover": "#00ffff",
        "error": "#ff0000",
        "warning": "#ffaa00",
        "success": "#00ff00",
        "orange": "#ff8800",
    },
    "Solar Claro": {
        "name": "Solar Claro",
        "bg": "#F8FAFC",
        "bg_secondary": "#FFFFFF",
        "fg": "#172033",
        "fg_muted": "#64748B",
        "fg_secondary": "#475569",
        "fg_tertiary": "#94A3B8",
        "accent": "#0EA5E9",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0284C7",
        "accent_dark": "#075985",
        "border": "#CBD5E1",
        "blue_hover": "#14B8A6",
        "error": "#DC2626",
        "warning": "#D97706",
        "success": "#16A34A",
        "orange": "#F59E0B",
    },
    "Bosque Operativo": {
        "name": "Bosque Operativo",
        "bg": "#07130F",
        "bg_secondary": "#10231D",
        "fg": "#F0FDF4",
        "fg_muted": "#A7C8B6",
        "fg_secondary": "#86A998",
        "fg_tertiary": "#638173",
        "accent": "#22C55E",
        "accent_light": "#86EFAC",
        "accent_hover": "#16A34A",
        "accent_dark": "#166534",
        "border": "#235341",
        "blue_hover": "#2DD4BF",
        "error": "#F87171",
        "warning": "#FBBF24",
        "success": "#4ADE80",
        "orange": "#A3E635",
    },
    "Amanecer Ambar": {
        "name": "Amanecer Ambar",
        "bg": "#1C1208",
        "bg_secondary": "#2A1A0D",
        "fg": "#FFF7ED",
        "fg_muted": "#D6B08A",
        "fg_secondary": "#C6925C",
        "fg_tertiary": "#92683C",
        "accent": "#F59E0B",
        "accent_light": "#FCD34D",
        "accent_hover": "#D97706",
        "accent_dark": "#92400E",
        "border": "#6B3E18",
        "blue_hover": "#38BDF8",
        "error": "#FB7185",
        "warning": "#FBBF24",
        "success": "#84CC16",
        "orange": "#FB923C",
    },
    "Neon Grid": {
        "name": "Neon Grid",
        "bg": "#070713",
        "bg_secondary": "#111126",
        "fg": "#F8FAFC",
        "fg_muted": "#A5B4FC",
        "fg_secondary": "#C4B5FD",
        "fg_tertiary": "#818CF8",
        "accent": "#22D3EE",
        "accent_light": "#67E8F9",
        "accent_hover": "#A855F7",
        "accent_dark": "#0891B2",
        "border": "#312E81",
        "blue_hover": "#F472B6",
        "error": "#FF4D8D",
        "warning": "#FACC15",
        "success": "#34D399",
        "orange": "#A855F7",
    },
    "Midnight Ocean": {
        "name": "Midnight Ocean",
        "bg": "#0A1628",
        "bg_secondary": "#142238",
        "fg": "#F0F9FF",
        "fg_muted": "#94A3B8",
        "fg_secondary": "#CBD5E1",
        "fg_tertiary": "#64748B",
        "accent": "#0EA5E9",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0284C7",
        "accent_dark": "#075985",
        "border": "#1E3A5F",
        "blue_hover": "#22D3EE",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#38BDF8",
    },
    "Forest Zen": {
        "name": "Forest Zen",
        "bg": "#0D1F14",
        "bg_secondary": "#16291D",
        "fg": "#F0FDF4",
        "fg_muted": "#86EFAC",
        "fg_secondary": "#BBF7D0",
        "fg_tertiary": "#4ADE80",
        "accent": "#22C55E",
        "accent_light": "#86EFAC",
        "accent_hover": "#16A34A",
        "accent_dark": "#15803D",
        "border": "#1E3A28",
        "blue_hover": "#14B8A6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#84CC16",
    },
    "Royal Purple": {
        "name": "Royal Purple",
        "bg": "#1A0B2E",
        "bg_secondary": "#2D1B4E",
        "fg": "#F5F3FF",
        "fg_muted": "#C4B5FD",
        "fg_secondary": "#DDD6FE",
        "fg_tertiary": "#A78BFA",
        "accent": "#8B5CF6",
        "accent_light": "#C4B5FD",
        "accent_hover": "#7C3AED",
        "accent_dark": "#5B21B6",
        "border": "#4C1D95",
        "blue_hover": "#EC4899",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F59E0B",
    },
    "Rose Quartz": {
        "name": "Rose Quartz",
        "bg": "#1F1115",
        "bg_secondary": "#2E1A20",
        "fg": "#FFF1F2",
        "fg_muted": "#FDA4AF",
        "fg_secondary": "#FECDD3",
        "fg_tertiary": "#FB7185",
        "accent": "#EC4899",
        "accent_light": "#F9A8D4",
        "accent_hover": "#DB2777",
        "accent_dark": "#BE185D",
        "border": "#4A1C24",
        "blue_hover": "#8B5CF6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F472B6",
    },
    "Arctic Frost": {
        "name": "Arctic Frost",
        "bg": "#F8FAFC",
        "bg_secondary": "#FFFFFF",
        "fg": "#0F172A",
        "fg_muted": "#64748B",
        "fg_secondary": "#475569",
        "fg_tertiary": "#94A3B8",
        "accent": "#0EA5E9",
        "accent_light": "#BAE6FD",
        "accent_hover": "#0284C7",
        "accent_dark": "#075985",
        "border": "#E2E8F0",
        "blue_hover": "#06B6D4",
        "error": "#DC2626",
        "warning": "#D97706",
        "success": "#059669",
        "orange": "#0EA5E9",
    },
    "Ember Glow": {
        "name": "Ember Glow",
        "bg": "#1A1208",
        "bg_secondary": "#2A1A0D",
        "fg": "#FFFBEB",
        "fg_muted": "#FCD34D",
        "fg_secondary": "#FDE68A",
        "fg_tertiary": "#FBBF24",
        "accent": "#F59E0B",
        "accent_light": "#FCD34D",
        "accent_hover": "#D97706",
        "accent_dark": "#B45309",
        "border": "#422006",
        "blue_hover": "#38BDF8",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#FB923C",
    },
    "Slate Modern": {
        "name": "Slate Modern",
        "bg": "#0F172A",
        "bg_secondary": "#1E293B",
        "fg": "#F8FAFC",
        "fg_muted": "#94A3B8",
        "fg_secondary": "#CBD5E1",
        "fg_tertiary": "#64748B",
        "accent": "#3B82F6",
        "accent_light": "#93C5FD",
        "accent_hover": "#2563EB",
        "accent_dark": "#1E40AF",
        "border": "#334155",
        "blue_hover": "#06B6D4",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#38BDF8",
    },
    "Aurora Borealis": {
        "name": "Aurora Borealis",
        "bg": "#0A0F1A",
        "bg_secondary": "#141B2D",
        "fg": "#F0F9FF",
        "fg_muted": "#7DD3FC",
        "fg_secondary": "#A5F3FC",
        "fg_tertiary": "#22D3EE",
        "accent": "#06B6D4",
        "accent_light": "#67E8F9",
        "accent_hover": "#0891B2",
        "accent_dark": "#0E7490",
        "border": "#164E63",
        "blue_hover": "#A855F7",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#22D3EE",
    },
    "Minimalist Cream": {
        "name": "Minimalist Cream",
        "bg": "#FFFBF0",
        "bg_secondary": "#FFFFFF",
        "fg": "#1C1917",
        "fg_muted": "#78716C",
        "fg_secondary": "#57534E",
        "fg_tertiary": "#A8A29E",
        "accent": "#78716C",
        "accent_light": "#D6D3D1",
        "accent_hover": "#57534E",
        "accent_dark": "#44403C",
        "border": "#E7E5E4",
        "blue_hover": "#0EA5E9",
        "error": "#DC2626",
        "warning": "#D97706",
        "success": "#059669",
        "orange": "#D97706",
    },
    "Cyberpunk": {
        "name": "Cyberpunk",
        "bg": "#050505",
        "bg_secondary": "#0A0A0A",
        "fg": "#FFFFFF",
        "fg_muted": "#FF00FF",
        "fg_secondary": "#00FFFF",
        "fg_tertiary": "#FFFF00",
        "accent": "#FF00FF",
        "accent_light": "#FF66FF",
        "accent_hover": "#CC00CC",
        "accent_dark": "#990099",
        "border": "#333333",
        "blue_hover": "#00FFFF",
        "error": "#FF0000",
        "warning": "#FFFF00",
        "success": "#00FF00",
        "orange": "#FF6600",
    },
    "Deep Space": {
        "name": "Deep Space",
        "bg": "#030712",
        "bg_secondary": "#0F172A",
        "fg": "#F8FAFC",
        "fg_muted": "#6366F1",
        "fg_secondary": "#818CF8",
        "fg_tertiary": "#4F46E5",
        "accent": "#6366F1",
        "accent_light": "#A5B4FC",
        "accent_hover": "#4F46E5",
        "accent_dark": "#3730A3",
        "border": "#1E1B4B",
        "blue_hover": "#22D3EE",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#8B5CF6",
    },
    "Golden Hour": {
        "name": "Golden Hour",
        "bg": "#1C1917",
        "bg_secondary": "#292524",
        "fg": "#FFFBEB",
        "fg_muted": "#FCD34D",
        "fg_secondary": "#FDE68A",
        "fg_tertiary": "#FBBF24",
        "accent": "#F59E0B",
        "accent_light": "#FCD34D",
        "accent_hover": "#D97706",
        "accent_dark": "#B45309",
        "border": "#44403C",
        "blue_hover": "#3B82F6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#FB923C",
    },
    "Lavender Dreams": {
        "name": "Lavender Dreams",
        "bg": "#1E1B4B",
        "bg_secondary": "#312E81",
        "fg": "#F5F3FF",
        "fg_muted": "#C4B5FD",
        "fg_secondary": "#DDD6FE",
        "fg_tertiary": "#A78BFA",
        "accent": "#8B5CF6",
        "accent_light": "#DDD6FE",
        "accent_hover": "#7C3AED",
        "accent_dark": "#5B21B6",
        "border": "#4338CA",
        "blue_hover": "#EC4899",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F472B6",
    },
    "Ocean Breeze": {
        "name": "Ocean Breeze",
        "bg": "#0C4A6E",
        "bg_secondary": "#075985",
        "fg": "#F0F9FF",
        "fg_muted": "#7DD3FC",
        "fg_secondary": "#BAE6FD",
        "fg_tertiary": "#38BDF8",
        "accent": "#0EA5E9",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0284C7",
        "accent_dark": "#0369A1",
        "border": "#0C4A6E",
        "blue_hover": "#22D3EE",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#06B6D4",
    },
    "Mars Red": {
        "name": "Mars Red",
        "bg": "#1C0A0A",
        "bg_secondary": "#2D1313",
        "fg": "#FEF2F2",
        "fg_muted": "#FCA5A5",
        "fg_secondary": "#FECACA",
        "fg_tertiary": "#F87171",
        "accent": "#EF4444",
        "accent_light": "#FCA5A5",
        "accent_hover": "#DC2626",
        "accent_dark": "#B91C1C",
        "border": "#450A0A",
        "blue_hover": "#3B82F6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F97316",
    },
    "Soft Pastel": {
        "name": "Soft Pastel",
        "bg": "#FAF7F5",
        "bg_secondary": "#FFFFFF",
        "fg": "#2C2420",
        "fg_muted": "#8C7B73",
        "fg_secondary": "#6B5E57",
        "fg_tertiary": "#A89B93",
        "accent": "#D4A373",
        "accent_light": "#E9C496",
        "accent_hover": "#B88A5A",
        "accent_dark": "#9A7048",
        "border": "#E8DDD5",
        "blue_hover": "#7DB9A8",
        "error": "#E07A7A",
        "warning": "#D4A373",
        "success": "#7DB9A8",
        "orange": "#E9C496",
    },
    "Nordic Frost": {
        "name": "Nordic Frost",
        "bg": "#F0F4F8",
        "bg_secondary": "#FFFFFF",
        "fg": "#1A202C",
        "fg_muted": "#4A5568",
        "fg_secondary": "#2D3748",
        "fg_tertiary": "#718096",
        "accent": "#4A90A4",
        "accent_light": "#90CDF4",
        "accent_hover": "#2C6F8A",
        "accent_dark": "#1A4A5E",
        "border": "#CBD5E0",
        "blue_hover": "#38B2AC",
        "error": "#E53E3E",
        "warning": "#DD6B20",
        "success": "#38A169",
        "orange": "#ED8936",
    },
    "Sakura Garden": {
        "name": "Sakura Garden",
        "bg": "#FFF5F7",
        "bg_secondary": "#FFFFFF",
        "fg": "#2D1F23",
        "fg_muted": "#8B6B73",
        "fg_secondary": "#6B4E56",
        "fg_tertiary": "#A88B93",
        "accent": "#EC407A",
        "accent_light": "#F48FB1",
        "accent_hover": "#D81B60",
        "accent_dark": "#AD1457",
        "border": "#F8BBD0",
        "blue_hover": "#26C6DA",
        "error": "#E53935",
        "warning": "#FB8C00",
        "success": "#43A047",
        "orange": "#FF8A65",
    },
    "Terminal Matrix": {
        "name": "Terminal Matrix",
        "bg": "#050805",
        "bg_secondary": "#0A120A",
        "fg": "#E8F5E9",
        "fg_muted": "#81C784",
        "fg_secondary": "#A5D6A7",
        "fg_tertiary": "#4CAF50",
        "accent": "#00E676",
        "accent_light": "#69F0AE",
        "accent_hover": "#00C853",
        "accent_dark": "#009624",
        "border": "#1B3A1B",
        "blue_hover": "#18FFFF",
        "error": "#FF5252",
        "warning": "#FFD740",
        "success": "#69F0AE",
        "orange": "#FFAB40",
    },
    "Obsidian Ember": {
        "name": "Obsidian Ember",
        "bg": "#0D0B0A",
        "bg_secondary": "#1A1614",
        "fg": "#FFF8E1",
        "fg_muted": "#FFB74D",
        "fg_secondary": "#FFE0B2",
        "fg_tertiary": "#BF8A4E",
        "accent": "#FF9100",
        "accent_light": "#FFD180",
        "accent_hover": "#FF6D00",
        "accent_dark": "#BF360C",
        "border": "#3E2723",
        "blue_hover": "#00BCD4",
        "error": "#FF5252",
        "warning": "#FFD740",
        "success": "#69F0AE",
        "orange": "#FFAB40",
    },
    "Twilight Lavender": {
        "name": "Twilight Lavender",
        "bg": "#1A1520",
        "bg_secondary": "#252030",
        "fg": "#F3E5F5",
        "fg_muted": "#CE93D8",
        "fg_secondary": "#E1BEE7",
        "fg_tertiary": "#AB47BC",
        "accent": "#AB47BC",
        "accent_light": "#CE93D8",
        "accent_hover": "#8E24AA",
        "accent_dark": "#6A1B9A",
        "border": "#4A148C",
        "blue_hover": "#26C6DA",
        "error": "#EF5350",
        "warning": "#FFA726",
        "success": "#66BB6A",
        "orange": "#FF8A65",
    },
    "Mint Chocolate": {
        "name": "Mint Chocolate",
        "bg": "#0F1512",
        "bg_secondary": "#182620",
        "fg": "#E8F5E9",
        "fg_muted": "#80CBC4",
        "fg_secondary": "#A7D8C9",
        "fg_tertiary": "#4DB6AC",
        "accent": "#26A69A",
        "accent_light": "#80CBC4",
        "accent_hover": "#00897B",
        "accent_dark": "#00695C",
        "border": "#264D40",
        "blue_hover": "#4DB6AC",
        "error": "#EF5350",
        "warning": "#FFB74D",
        "success": "#66BB6A",
        "orange": "#FF8A65",
    },
    "Coral Sunset": {
        "name": "Coral Sunset",
        "bg": "#1A1210",
        "bg_secondary": "#251A16",
        "fg": "#FFF3E0",
        "fg_muted": "#FFAB91",
        "fg_secondary": "#FFCCBC",
        "fg_tertiary": "#BF360C",
        "accent": "#FF7043",
        "accent_light": "#FFAB91",
        "accent_hover": "#F4511E",
        "accent_dark": "#BF360C",
        "border": "#3E2723",
        "blue_hover": "#40C4FF",
        "error": "#FF5252",
        "warning": "#FFD740",
        "success": "#69F0AE",
        "orange": "#FFAB40",
    },
    "Paper White": {
        "name": "Paper White",
        "bg": "#FFFFFF",
        "bg_secondary": "#F8FAFC",
        "fg": "#0F172A",
        "fg_muted": "#475569",
        "fg_secondary": "#334155",
        "fg_tertiary": "#94A3B8",
        "accent": "#0F172A",
        "accent_light": "#CBD5E1",
        "accent_hover": "#1E293B",
        "accent_dark": "#020617",
        "border": "#E2E8F0",
        "blue_hover": "#0EA5E9",
        "error": "#DC2626",
        "warning": "#D97706",
        "success": "#059669",
        "orange": "#F59E0B",
    },
    "Deep Forest": {
        "name": "Deep Forest",
        "bg": "#08140E",
        "bg_secondary": "#11221A",
        "fg": "#ECFDF5",
        "fg_muted": "#6EE7B7",
        "fg_secondary": "#A7F3D0",
        "fg_tertiary": "#34D399",
        "accent": "#059669",
        "accent_light": "#34D399",
        "accent_hover": "#047857",
        "accent_dark": "#065F46",
        "border": "#1E3A2F",
        "blue_hover": "#2DD4BF",
        "error": "#F87171",
        "warning": "#FBBF24",
        "success": "#34D399",
        "orange": "#A3E635",
    },
    "Void Black": {
        "name": "Void Black",
        "bg": "#050505",
        "bg_secondary": "#0E0E0E",
        "fg": "#E5E5E5",
        "fg_muted": "#737373",
        "fg_secondary": "#A3A3A3",
        "fg_tertiary": "#525252",
        "accent": "#A855F7",
        "accent_light": "#D8B4FE",
        "accent_hover": "#9333EA",
        "accent_dark": "#6B21A8",
        "border": "#262626",
        "blue_hover": "#C084FC",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#F97316",
    },
    "Noir Cinema": {
        "name": "Noir Cinema",
        "bg": "#0A0A0A",
        "bg_secondary": "#141414",
        "fg": "#F5F5F5",
        "fg_muted": "#A1A1AA",
        "fg_secondary": "#D4D4D8",
        "fg_tertiary": "#71717A",
        "accent": "#E4E4E7",
        "accent_light": "#FAFAFA",
        "accent_hover": "#D4D4D8",
        "accent_dark": "#52525B",
        "border": "#27272A",
        "blue_hover": "#FFFFFF",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#FB923C",
    },
    "Inferno Crimson": {
        "name": "Inferno Crimson",
        "bg": "#1A0505",
        "bg_secondary": "#2A0A0A",
        "fg": "#FFF5F5",
        "fg_muted": "#FCA5A5",
        "fg_secondary": "#FECACA",
        "fg_tertiary": "#EF4444",
        "accent": "#DC2626",
        "accent_light": "#FCA5A5",
        "accent_hover": "#B91C1C",
        "accent_dark": "#7F1D1D",
        "border": "#450A0A",
        "blue_hover": "#F87171",
        "error": "#EF4444",
        "warning": "#FBBF24",
        "success": "#34D399",
        "orange": "#FB923C",
    },
    "Electric Lime": {
        "name": "Electric Lime",
        "bg": "#0A0F00",
        "bg_secondary": "#141F00",
        "fg": "#F7FEE7",
        "fg_muted": "#BEF264",
        "fg_secondary": "#D9F99D",
        "fg_tertiary": "#84CC16",
        "accent": "#65A30D",
        "accent_light": "#BEF264",
        "accent_hover": "#4D7C0F",
        "accent_dark": "#365314",
        "border": "#1A2E05",
        "blue_hover": "#A3E635",
        "error": "#EF4444",
        "warning": "#FACC15",
        "success": "#4ADE80",
        "orange": "#FB923C",
    },
    "Berry Wine": {
        "name": "Berry Wine",
        "bg": "#1A0510",
        "bg_secondary": "#2A0A1A",
        "fg": "#FFF0F5",
        "fg_muted": "#F9A8D4",
        "fg_secondary": "#FBCFE8",
        "fg_tertiary": "#DB2777",
        "accent": "#BE185D",
        "accent_light": "#F9A8D4",
        "accent_hover": "#9D174D",
        "accent_dark": "#831843",
        "border": "#500724",
        "blue_hover": "#F472B6",
        "error": "#EF4444",
        "warning": "#FBBF24",
        "success": "#34D399",
        "orange": "#FB923C",
    },
    "Gunmetal Gray": {
        "name": "Gunmetal Gray",
        "bg": "#0F1115",
        "bg_secondary": "#1A1D23",
        "fg": "#F1F5F9",
        "fg_muted": "#94A3B8",
        "fg_secondary": "#CBD5E1",
        "fg_tertiary": "#64748B",
        "accent": "#94A3B8",
        "accent_light": "#CBD5E1",
        "accent_hover": "#64748B",
        "accent_dark": "#475569",
        "border": "#334155",
        "blue_hover": "#38BDF8",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#F97316",
    },
    "Nordic Night": {
        "name": "Nordic Night",
        "bg": "#0B1120",
        "bg_secondary": "#111B2E",
        "fg": "#E2E8F0",
        "fg_muted": "#7AA7C7",
        "fg_secondary": "#A5C4D9",
        "fg_tertiary": "#5A8FAF",
        "accent": "#5A8FAF",
        "accent_light": "#A5C4D9",
        "accent_hover": "#4A7F9F",
        "accent_dark": "#3A6F8F",
        "border": "#1E3A5F",
        "blue_hover": "#7AA7C7",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#F97316",
    },
    "Blood Moon": {
        "name": "Blood Moon",
        "bg": "#1A0A00",
        "bg_secondary": "#2A1000",
        "fg": "#FFF7ED",
        "fg_muted": "#FB923C",
        "fg_secondary": "#FDBA74",
        "fg_tertiary": "#EA580C",
        "accent": "#C2410C",
        "accent_light": "#FB923C",
        "accent_hover": "#9A3412",
        "accent_dark": "#7C2D12",
        "border": "#431407",
        "blue_hover": "#F97316",
        "error": "#EF4444",
        "warning": "#FACC15",
        "success": "#22C55E",
        "orange": "#FB923C",
    },
    "Dark Matter": {
        "name": "Dark Matter",
        "bg": "#0A0814",
        "bg_secondary": "#141024",
        "fg": "#F5F3FF",
        "fg_muted": "#8B5CF6",
        "fg_secondary": "#A78BFA",
        "fg_tertiary": "#6D28D9",
        "accent": "#7C3AED",
        "accent_light": "#A78BFA",
        "accent_hover": "#6D28D9",
        "accent_dark": "#5B21B6",
        "border": "#2E1065",
        "blue_hover": "#8B5CF6",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#F97316",
    },
    "Volcanic Ash": {
        "name": "Volcanic Ash",
        "bg": "#1C1C1C",
        "bg_secondary": "#2A2A2A",
        "fg": "#F5F5F5",
        "fg_muted": "#A3A3A3",
        "fg_secondary": "#D4D4D4",
        "fg_tertiary": "#737373",
        "accent": "#DC2626",
        "accent_light": "#FCA5A5",
        "accent_hover": "#B91C1C",
        "accent_dark": "#991B1B",
        "border": "#404040",
        "blue_hover": "#F87171",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#FB923C",
    },
    "Polar Night": {
        "name": "Polar Night",
        "bg": "#0B1221",
        "bg_secondary": "#111E33",
        "fg": "#F0F9FF",
        "fg_muted": "#7DD3FC",
        "fg_secondary": "#BAE6FD",
        "fg_tertiary": "#38BDF8",
        "accent": "#0284C7",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0369A1",
        "accent_dark": "#075985",
        "border": "#164E63",
        "blue_hover": "#38BDF8",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#F97316",
    },
    "Shadow Gray": {
        "name": "Shadow Gray",
        "bg": "#18181B",
        "bg_secondary": "#27272A",
        "fg": "#FAFAFA",
        "fg_muted": "#A1A1AA",
        "fg_secondary": "#D4D4D8",
        "fg_tertiary": "#71717A",
        "accent": "#D4D4D8",
        "accent_light": "#E4E4E7",
        "accent_hover": "#A1A1AA",
        "accent_dark": "#52525B",
        "border": "#3F3F46",
        "blue_hover": "#A1A1AA",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#F97316",
    },
    "Pitch Black": {
        "name": "Pitch Black",
        "bg": "#000000",
        "bg_secondary": "#080808",
        "fg": "#FFFFFF",
        "fg_muted": "#555555",
        "fg_secondary": "#AAAAAA",
        "fg_tertiary": "#333333",
        "accent": "#FF0000",
        "accent_light": "#FF5555",
        "accent_hover": "#CC0000",
        "accent_dark": "#990000",
        "border": "#1A1A1A",
        "blue_hover": "#FF3333",
        "error": "#FF0000",
        "warning": "#FFAA00",
        "success": "#00FF00",
        "orange": "#FF4400",
    },
    "Carbon Black": {
        "name": "Carbon Black",
        "bg": "#020202",
        "bg_secondary": "#0A0A0A",
        "fg": "#F0F0F0",
        "fg_muted": "#606060",
        "fg_secondary": "#999999",
        "fg_tertiary": "#404040",
        "accent": "#00D4AA",
        "accent_light": "#66FFCC",
        "accent_hover": "#00B894",
        "accent_dark": "#008F6B",
        "border": "#1C1C1C",
        "blue_hover": "#00FFC8",
        "error": "#FF4444",
        "warning": "#FFAA00",
        "success": "#00FF88",
        "orange": "#FF6600",
    },
    "Onyx Black": {
        "name": "Onyx Black",
        "bg": "#0C0C0C",
        "bg_secondary": "#151515",
        "fg": "#EDEDED",
        "fg_muted": "#707070",
        "fg_secondary": "#A0A0A0",
        "fg_tertiary": "#505050",
        "accent": "#C0A062",
        "accent_light": "#E8D5A3",
        "accent_hover": "#A08040",
        "accent_dark": "#705820",
        "border": "#242424",
        "blue_hover": "#D4B87A",
        "error": "#E05050",
        "warning": "#E0A040",
        "success": "#50C878",
        "orange": "#E08030",
    },
    "Obsidian Black": {
        "name": "Obsidian Black",
        "bg": "#070707",
        "bg_secondary": "#111111",
        "fg": "#E8E8E8",
        "fg_muted": "#666666",
        "fg_secondary": "#999999",
        "fg_tertiary": "#444444",
        "accent": "#E0E0E0",
        "accent_light": "#FFFFFF",
        "accent_hover": "#B0B0B0",
        "accent_dark": "#707070",
        "border": "#222222",
        "blue_hover": "#FFFFFF",
        "error": "#FF3333",
        "warning": "#FFBB33",
        "success": "#33FF57",
        "orange": "#FF7733",
    },
    "Charcoal Black": {
        "name": "Charcoal Black",
        "bg": "#141414",
        "bg_secondary": "#1E1E1E",
        "fg": "#F2F2F2",
        "fg_muted": "#777777",
        "fg_secondary": "#AAAAAA",
        "fg_tertiary": "#555555",
        "accent": "#4ECDC4",
        "accent_light": "#96E6D6",
        "accent_hover": "#3DBBB0",
        "accent_dark": "#2A9088",
        "border": "#2A2A2A",
        "blue_hover": "#6EF0E0",
        "error": "#FF6B6B",
        "warning": "#FFD93D",
        "success": "#6BCB77",
        "orange": "#FF8C42",
    },
    "Ink Black": {
        "name": "Ink Black",
        "bg": "#0D0D0D",
        "bg_secondary": "#161616",
        "fg": "#F5F5F5",
        "fg_muted": "#757575",
        "fg_secondary": "#A5A5A5",
        "fg_tertiary": "#505050",
        "accent": "#FF2E63",
        "accent_light": "#FF6B9D",
        "accent_hover": "#D61C4E",
        "accent_dark": "#A01038",
        "border": "#262626",
        "blue_hover": "#FF5C8D",
        "error": "#FF2E63",
        "warning": "#FFC947",
        "success": "#28DF99",
        "orange": "#FF9F45",
    },
    "Raven Black": {
        "name": "Raven Black",
        "bg": "#09090B",
        "bg_secondary": "#121214",
        "fg": "#F4F4F5",
        "fg_muted": "#71717A",
        "fg_secondary": "#A1A1AA",
        "fg_tertiary": "#52525B",
        "accent": "#8B5CF6",
        "accent_light": "#C4B5FD",
        "accent_hover": "#7C3AED",
        "accent_dark": "#6D28D9",
        "border": "#27272A",
        "blue_hover": "#A78BFA",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F97316",
    },
    "Abyss Black": {
        "name": "Abyss Black",
        "bg": "#030305",
        "bg_secondary": "#0A0A0F",
        "fg": "#E2E8F0",
        "fg_muted": "#475569",
        "fg_secondary": "#64748B",
        "fg_tertiary": "#334155",
        "accent": "#0EA5E9",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0284C7",
        "accent_dark": "#0369A1",
        "border": "#1E293B",
        "blue_hover": "#38BDF8",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F97316",
    },
    "Jet Black": {
        "name": "Jet Black",
        "bg": "#101012",
        "bg_secondary": "#1A1A1D",
        "fg": "#FAFAFA",
        "fg_muted": "#6B7280",
        "fg_secondary": "#9CA3AF",
        "fg_tertiary": "#4B5563",
        "accent": "#F472B6",
        "accent_light": "#F9A8D4",
        "accent_hover": "#EC4899",
        "accent_dark": "#DB2777",
        "border": "#374151",
        "blue_hover": "#FBB6D0",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F97316",
    },
    "Soot Black": {
        "name": "Soot Black",
        "bg": "#0A0A0C",
        "bg_secondary": "#131316",
        "fg": "#F8FAFC",
        "fg_muted": "#64748B",
        "fg_secondary": "#94A3B8",
        "fg_tertiary": "#475569",
        "accent": "#22D3EE",
        "accent_light": "#67E8F9",
        "accent_hover": "#06B6D4",
        "accent_dark": "#0891B2",
        "border": "#1E293B",
        "blue_hover": "#A5F3FC",
        "error": "#F87171",
        "warning": "#FBBF24",
        "success": "#34D399",
        "orange": "#FB923C",
    },
    "Ebony Black": {
        "name": "Ebony Black",
        "bg": "#12100E",
        "bg_secondary": "#1C1917",
        "fg": "#FAFAF9",
        "fg_muted": "#78716C",
        "fg_secondary": "#A8A29E",
        "fg_tertiary": "#57534E",
        "accent": "#D97706",
        "accent_light": "#FCD34D",
        "accent_hover": "#B45309",
        "accent_dark": "#92400E",
        "border": "#44403C",
        "blue_hover": "#FBBF24",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#F97316",
    },
    "Titanium Black": {
        "name": "Titanium Black",
        "bg": "#0E0E10",
        "bg_secondary": "#18181B",
        "fg": "#F4F4F5",
        "fg_muted": "#71717A",
        "fg_secondary": "#A1A1AA",
        "fg_tertiary": "#52525B",
        "accent": "#A1A1AA",
        "accent_light": "#D4D4D8",
        "accent_hover": "#71717A",
        "accent_dark": "#52525B",
        "border": "#27272A",
        "blue_hover": "#E4E4E7",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#22C55E",
        "orange": "#F97316",
    },
    "Midnight Black": {
        "name": "Midnight Black",
        "bg": "#05050A",
        "bg_secondary": "#0D0D18",
        "fg": "#EEF2FF",
        "fg_muted": "#6366F1",
        "fg_secondary": "#818CF8",
        "fg_tertiary": "#4338CA",
        "accent": "#6366F1",
        "accent_light": "#A5B4FC",
        "accent_hover": "#4F46E5",
        "accent_dark": "#3730A3",
        "border": "#1E1B4B",
        "blue_hover": "#818CF8",
        "error": "#EF4444",
        "warning": "#F59E0B",
        "success": "#10B981",
        "orange": "#F97316",
    },
    "Phantom Black": {
        "name": "Phantom Black",
        "bg": "#080808",
        "bg_secondary": "#121212",
        "fg": "#F0F0F0",
        "fg_muted": "#888888",
        "fg_secondary": "#BBBBBB",
        "fg_tertiary": "#555555",
        "accent": "#39FF14",
        "accent_light": "#8AFF6E",
        "accent_hover": "#2ECC10",
        "accent_dark": "#1A990A",
        "border": "#1E1E1E",
        "blue_hover": "#66FF44",
        "error": "#FF3333",
        "warning": "#FFDD33",
        "success": "#39FF14",
        "orange": "#FF8822",
    },
    "Velvet Black": {
        "name": "Velvet Black",
        "bg": "#0F050F",
        "bg_secondary": "#1A0A1A",
        "fg": "#FFF0FF",
        "fg_muted": "#D8A0D8",
        "fg_secondary": "#E8C0E8",
        "fg_tertiary": "#A060A0",
        "accent": "#DA70D6",
        "accent_light": "#EEAAEE",
        "accent_hover": "#C850C8",
        "accent_dark": "#903090",
        "border": "#3A153A",
        "blue_hover": "#E8A0E8",
        "error": "#FF4444",
        "warning": "#FFAA00",
        "success": "#44FF88",
        "orange": "#FF7744",
    },
    "Storm Black": {
        "name": "Storm Black",
        "bg": "#0A0F14",
        "bg_secondary": "#121820",
        "fg": "#F0F4F8",
        "fg_muted": "#5A7A96",
        "fg_secondary": "#7A9AB6",
        "fg_tertiary": "#4A6A86",
        "accent": "#5A7A96",
        "accent_light": "#8AABCC",
        "accent_hover": "#4A6A86",
        "accent_dark": "#3A5A76",
        "border": "#1E2E3E",
        "blue_hover": "#7A9AB6",
        "error": "#CC5555",
        "warning": "#DDA020",
        "success": "#55AA77",
        "orange": "#DD8844",
    },
    "Blindaje Black": {
        "name": "Blindaje Black",
        "bg": "#0D0D0D",
        "bg_secondary": "#181818",
        "fg": "#E5E5E5",
        "fg_muted": "#808080",
        "fg_secondary": "#B0B0B0",
        "fg_tertiary": "#505050",
        "accent": "#FFD700",
        "accent_light": "#FFEC8B",
        "accent_hover": "#D4AF37",
        "accent_dark": "#B8860B",
        "border": "#2A2A2A",
        "blue_hover": "#FFE55C",
        "error": "#FF4444",
        "warning": "#FFAA00",
        "success": "#00FF00",
        "orange": "#FF8800",
    },
    "Dracula Black": {
        "name": "Dracula Black",
        "bg": "#0B0B10",
        "bg_secondary": "#141420",
        "fg": "#F8F8F2",
        "fg_muted": "#6272A4",
        "fg_secondary": "#8BE9FD",
        "fg_tertiary": "#44475A",
        "accent": "#BD93F9",
        "accent_light": "#D6ACFF",
        "accent_hover": "#A366F5",
        "accent_dark": "#8A4DFF",
        "border": "#282A36",
        "blue_hover": "#8BE9FD",
        "error": "#FF5555",
        "warning": "#F1FA8C",
        "success": "#50FA7B",
        "orange": "#FFB86C",
    },
    "Black Ops": {
        "name": "Black Ops",
        "bg": "#060606",
        "bg_secondary": "#101010",
        "fg": "#E8E8E8",
        "fg_muted": "#555555",
        "fg_secondary": "#888888",
        "fg_tertiary": "#333333",
        "accent": "#FF3B3B",
        "accent_light": "#FF8080",
        "accent_hover": "#D63030",
        "accent_dark": "#A82020",
        "border": "#1A1A1A",
        "blue_hover": "#FF6060",
        "error": "#FF0000",
        "warning": "#FFAA00",
        "success": "#00CC44",
        "orange": "#FF4400",
    },
    "Vanta Black": {
        "name": "Vanta Black",
        "bg": "#000000",
        "bg_secondary": "#050505",
        "fg": "#FFFFFF",
        "fg_muted": "#333333",
        "fg_secondary": "#666666",
        "fg_tertiary": "#1A1A1A",
        "accent": "#00FF88",
        "accent_light": "#55FFAA",
        "accent_hover": "#00CC66",
        "accent_dark": "#009944",
        "border": "#111111",
        "blue_hover": "#33FF99",
        "error": "#FF2222",
        "warning": "#FFBB00",
        "success": "#00FF66",
        "orange": "#FF5500",
    },
    "Stealth Black": {
        "name": "Stealth Black",
        "bg": "#080A0C",
        "bg_secondary": "#111418",
        "fg": "#F1F5F9",
        "fg_muted": "#475569",
        "fg_secondary": "#64748B",
        "fg_tertiary": "#334155",
        "accent": "#38BDF8",
        "accent_light": "#7DD3FC",
        "accent_hover": "#0EA5E9",
        "accent_dark": "#0284C7",
        "border": "#1E293B",
        "blue_hover": "#7DD3FC",
        "error": "#F87171",
        "warning": "#FBBF24",
        "success": "#34D399",
        "orange": "#FB923C",
    },
    "Ace of Spades": {
        "name": "Ace of Spades",
        "bg": "#0C0C0C",
        "bg_secondary": "#161616",
        "fg": "#F0F0F0",
        "fg_muted": "#666666",
        "fg_secondary": "#999999",
        "fg_tertiary": "#444444",
        "accent": "#FFD700",
        "accent_light": "#FFEA80",
        "accent_hover": "#D4AF37",
        "accent_dark": "#B8860B",
        "border": "#222222",
        "blue_hover": "#FFE135",
        "error": "#FF3333",
        "warning": "#FFCC00",
        "success": "#00FF66",
        "orange": "#FF7700",
    },
}

_CONFIG_PATH: Path | None = None


def _config_file() -> Path:
    global _CONFIG_PATH
    if _CONFIG_PATH is None:
        _CONFIG_PATH = user_data_path("theme_config.json")
    return _CONFIG_PATH


def load_theme() -> dict[str, str]:
    """Carga el tema desde disco o retorna el default."""
    path = _config_file()
    if path.exists():
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict) and "bg" in data:
                theme = dict(DEFAULT_THEME)
                theme.update(data)
                return theme
        except (json.JSONDecodeError, OSError, TypeError) as exc:
            logger.warning("Error leyendo configuración de tema, usando default: %s", exc)
    return dict(DEFAULT_THEME)


def save_theme(theme: dict[str, Any]) -> dict[str, str]:
    """Guarda el tema en disco."""
    path = _config_file()
    validated: dict[str, str] = {}
    for k, v in theme.items():
        if isinstance(v, str) and v.startswith("#"):
            validated[k] = v
        else:
            validated[k] = str(v)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(validated, f, indent=2, ensure_ascii=False)
    return validated


def reset_theme() -> dict[str, str]:
    """Restaura el tema por defecto."""
    save_theme(DEFAULT_THEME)
    return dict(DEFAULT_THEME)


def get_preset_names() -> list[str]:
    """Retorna la lista de nombres de presets disponibles."""
    return list(PRESETS.keys())


def load_preset(name: str) -> dict[str, str]:
    """Retorna una copia del preset solicitado o el default si no existe."""
    preset = PRESETS.get(name)
    if preset:
        return dict(preset)
    return dict(DEFAULT_THEME)
