# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

block_cipher = None

backend_dir = Path(sys._getframe().f_code.co_filename).parent.resolve()
project_dir = backend_dir.parent

a = Analysis(
    [str(backend_dir / 'main.py')],
    pathex=[str(backend_dir), str(project_dir)],
    binaries=[],
    datas=[
        (str(backend_dir / 'templates'), 'backend/templates'),
        (str(backend_dir / 'core' / 'presets.json'), 'backend/core'),
    ],
    hiddenimports=[
        'backend.core.converter',
        'backend.core.database',
        'backend.core.renamer',
        'backend.core.config_fields',
        'backend.core.config_theme',
        'backend.core.plugins',
        'backend.core.history',
        'backend.core.format_registry',
        'backend.core.formatos',
        'backend.core.technical_reports',
        'backend.core.technical_reports.models',
        'backend.core.technical_reports.database',
        'backend.core.technical_reports.importer',
        'backend.core.technical_reports.rendering',
        'backend.utils.validators',
        'backend.utils.paths',
        'backend.ipc_protocol',
        'backend.handlers',
        'backend.version',
        'jinja2',
        'weasyprint',
        'weasyprint.css',
        'weasyprint.text',
        'weasyprint.layout',
        'weasyprint.images',
        'weasyprint.pdf',
        'weasyprint.formatting_structure',
        'PIL',
        'PIL._imagingtk',
        'PIL.Image',
        'pandas',
        'pandas._libs.tslibs',
        'openpyxl',
        'pypdf',
        'pypdf.generic',
        'pypdf.generic._data_structures',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
excludes=[
        # Optional acceleration/analytics stacks pulled in by pandas hooks.
        # The app uses pandas/openpyxl for Excel I/O, not SciPy/Numba.
        'scipy',
        'numba',
        'llvmlite',
        'pandas._testing',
        'numpy.testing',
        # Unused large modules
        'matplotlib',
        'notebook',
        'IPython',
        'jupyterlab',
        'tornado',
        'sqlalchemy',
        'pydoc',
        'doctest',
        'pip',
        'tkinter',
        'test',
        'tests',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=True,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AntaresBackend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
